import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../generated/prisma/client";

const prisma=new PrismaClient({adapter:new PrismaPg({connectionString:process.env.DATABASE_URL!})});
const daysAgo=(days:number)=>new Date(Date.now()-days*86400000);
const todayUtc=()=>new Date(new Date().toISOString().slice(0,10)+"T00:00:00.000Z");

async function main(){
 const organization=await prisma.organization.findFirst({where:{code:{startsWith:"ORG-"}},include:{branches:true}});if(!organization||!organization.branches[0])throw new Error("Bootstrap the organisation before seeding demo data");
 const branch=organization.branches[0];
 await prisma.examResult.deleteMany({where:{exam:{branchId:branch.id}}});await prisma.exam.deleteMany({where:{branchId:branch.id}});await prisma.attendanceRecord.deleteMany({where:{branchId:branch.id}});await prisma.feePayment.deleteMany({where:{invoice:{branchId:branch.id}}});await prisma.feeInvoice.deleteMany({where:{branchId:branch.id}});await prisma.student.deleteMany({where:{branchId:branch.id,email:{endsWith:"@demo.idealdigiskills.local"}}});await prisma.batch.deleteMany({where:{branchId:branch.id,code:{startsWith:"DEMO-"}}});await prisma.course.deleteMany({where:{organizationId:organization.id,code:{startsWith:"DEMO-"}}});await prisma.visitEnquiry.deleteMany({where:{branchId:branch.id,email:{endsWith:"@demo.idealdigiskills.local"}}});
 const courseSpecs=[{name:"Advanced Computer Applications",code:"DEMO-ADCA",category:"COMPUTER" as const,fee:36000,duration:12},{name:"Digital Marketing & Design",code:"DEMO-DMD",category:"SKILL_DEVELOPMENT" as const,fee:28000,duration:6},{name:"Tally & Business Accounting",code:"DEMO-TBA",category:"VOCATIONAL" as const,fee:24000,duration:6}];
 const courses:Array<{id:string;baseFee:number;name:string}>=[];for(const c of courseSpecs)courses.push(await prisma.course.create({data:{organizationId:organization.id,name:c.name,code:c.code,category:c.category,durationValue:c.duration,durationUnit:"MONTHS",baseFee:c.fee,registrationFee:1000,examFee:1500,description:"Demo course for product evaluation"}}));
 const batches=[];for(let i=0;i<courses.length;i++)batches.push(await prisma.batch.create({data:{branchId:branch.id,courseId:courses[i].id,name:["Morning A","Afternoon B","Evening A"][i],code:`DEMO-BATCH-${i+1}`,maxSeats:30,startDate:daysAgo(45-i*8),endDate:new Date(Date.now()+(180+i*30)*86400000),status:"ACTIVE"}}));
 const people=["Aarav Sharma","Ananya Verma","Arjun Mehta","Diya Roy","Ishaan Gupta","Kavya Nair","Krish Patel","Meera Singh","Rohan Das","Saanvi Bose","Vihaan Kumar","Zoya Khan"];
 const students=[];for(let i=0;i<people.length;i++){const [firstName,...last]=people[i].split(" ");students.push(await prisma.student.create({data:{branchId:branch.id,courseId:courses[i%3].id,batchId:batches[i%3].id,enrollmentNo:`DEMO-STU-${String(i+1).padStart(3,"0")}`,applicationNo:`DEMO-APP-${String(i+1).padStart(3,"0")}`,firstName,lastName:last.join(" "),dateOfBirth:new Date(2003+(i%4),i%12,(i%25)+1),gender:i%2?"FEMALE":"MALE",phone:`900000${String(1000+i).slice(-4)}`,email:`student${i+1}@demo.idealdigiskills.local`,streetAddress:`${21+i}, Demo Learning Road`,city:"Kolkata",state:"West Bengal",district:"Kolkata",pincode:"700001",fatherName:`Demo Guardian ${i+1}`,motherName:`Demo Parent ${i+1}`,academicYear:"2026-27",admissionStatus:i<10?"APPROVED":"SUBMITTED",isActive:true,admissionDate:daysAgo(40-i)}}));}
 const receiver=await prisma.user.findFirstOrThrow({where:{id:organization.userId}});
 for(let i=0;i<students.length;i++){const amount=Number(courses[i%3].baseFee);const invoice=await prisma.feeInvoice.create({data:{studentId:students[i].id,branchId:branch.id,invoiceNo:`DEMO-INV-${String(i+1).padStart(3,"0")}`,description:"Course tuition fee",amount,dueDate:new Date(Date.now()+(i-5)*86400000),status:i%4===0?"DUE":i%4===1?"PARTIAL":"PAID"}});const paid=i%4===0?0:i%4===1?Math.round(amount/2):amount;if(paid)await prisma.feePayment.create({data:{invoiceId:invoice.id,receiptNo:`DEMO-RCT-${String(i+1).padStart(3,"0")}`,amount:paid,method:i%2?"UPI":"CASH",referenceNo:i%2?`DEMO-UPI-${i+1}`:undefined,receivedById:receiver.id,paidAt:daysAgo(i%12)}});}
 for(let day=0;day<14;day++){const date=new Date(todayUtc().getTime()-day*86400000);for(let i=0;i<students.length;i++)await prisma.attendanceRecord.create({data:{studentId:students[i].id,branchId:branch.id,batchId:students[i].batchId,date,status:(i+day)%11===0?"ABSENT":(i+day)%7===0?"LATE":"PRESENT",markedById:receiver.id}});}
 for(let i=0;i<courses.length;i++){for(const [position,subject] of ["Theory","Practical"].entries()){const exam=await prisma.exam.create({data:{branchId:branch.id,courseId:courses[i].id,batchId:batches[i].id,name:"Final Assessment 2026",subject:`${courses[i].name} - ${subject}`,examDate:daysAgo(8-position),maxMarks:100,passMarks:40,status:"PUBLISHED"}});const enrolled=students.filter(student=>student.courseId===courses[i].id);for(let j=0;j<enrolled.length;j++)await prisma.examResult.create({data:{examId:exam.id,studentId:enrolled[j].id,marks:62+((i*7+j*9+position*5)%34),remarks:"Demonstrated practical understanding"}});}}
 for(let i=0;i<8;i++)await prisma.visitEnquiry.create({data:{branchId:branch.id,visitorName:["Neha Kapoor","Rahul Sen","Pooja Shah","Amit Jain","Nisha Rao","Samir Paul","Tanya Ghosh","Karan Malhotra"][i],phone:`98888000${10+i}`,email:`enquiry${i+1}@demo.idealdigiskills.local`,visitDate:daysAgo(i%4),visitTime:`${10+(i%7)}:30`,purpose:i%3===0?"ADMISSION":i%3===1?"FEE":"MEETING",personToMeet:i%3===0?"Admission Counsellor":i%3===1?"Accounts":"Branch Director",department:i%3===1?"ACCOUNTS":"ADMINISTRATION",enquiryReason:"Demo enquiry created for product evaluation"}});
 console.log(JSON.stringify({organization:organization.name,branch:branch.name,courses:courses.length,batches:batches.length,students:students.length,invoices:students.length,attendance:students.length*14,exams:courses.length*2,results:students.length*2,enquiries:8},null,2));
}
main().finally(()=>prisma.$disconnect());
