import { Router } from "express";
import { z } from "zod";
import { prisma } from "../../db";
import { authenticate, permit } from "../../middlewares/auth.middleware";
import { asyncHandler } from "../../utils/async.utils";
import { audit } from "../../utils/audit.utils";
import { documentNo } from "../../utils/id.utils";
import { ErrorResponse } from "../../utils/response.utils";

// Money is stored as DECIMAL(12,2); compare in integer paise so float drift can
// never decide whether an invoice is fully PAID or still PARTIAL.
const paise = (value: unknown) => Math.round(Number(value ?? 0) * 100);

const router=Router();router.use(authenticate);
const branch=(req:Express.Request)=>req.auth!.branchId!; const org=(req:Express.Request)=>req.auth!.organizationId!;
const paging=(query:unknown)=>{const q=z.object({page:z.coerce.number().min(1).default(1),limit:z.coerce.number().min(1).max(100).default(20),search:z.string().optional()}).parse(query);return {...q,skip:(q.page-1)*q.limit}};

router.get("/dashboard",asyncHandler(async(req,res)=>{const branchId=branch(req);const monthStart=new Date(new Date().getFullYear(),new Date().getMonth(),1);const today=new Date(new Date().toISOString().slice(0,10)+"T00:00:00.000Z");const [students,enquiries,due,attendance,payments,courses]=await Promise.all([prisma.student.count({where:{branchId,isActive:true,deletedAt:null}}),prisma.visitEnquiry.count({where:{branchId,createdAt:{gte:new Date(new Date().setHours(0,0,0,0))}}}),prisma.feeInvoice.findMany({where:{branchId,status:{in:["DUE","PARTIAL"]}},include:{payments:{where:{reversedAt:null}}}}),prisma.attendanceRecord.groupBy({by:["status"],where:{branchId,date:today},_count:true}),prisma.feePayment.aggregate({where:{invoice:{branchId},reversedAt:null,paidAt:{gte:monthStart}},_sum:{amount:true}}),prisma.course.count({where:{organizationId:org(req),isActive:true,deletedAt:null}})]);const outstanding=due.reduce((sum,invoice)=>sum+Number(invoice.amount)-invoice.payments.reduce((paid,p)=>paid+Number(p.amount),0),0);const attendanceTotal=attendance.reduce((sum,row)=>sum+row._count,0);const present=attendance.filter(row=>row.status==="PRESENT"||row.status==="LATE").reduce((sum,row)=>sum+row._count,0);res.json({success:true,data:{students,enquiriesToday:enquiries,outstanding,feesCollected:Number(payments._sum.amount||0),courses,attendancePercentage:attendanceTotal?Math.round(present/attendanceTotal*1000)/10:0,attendance}});}));

router.get("/batches",asyncHandler(async(req,res)=>{const data=await prisma.batch.findMany({where:{branchId:branch(req),isActive:true},include:{course:true,_count:{select:{students:true}},timings:true},orderBy:{startDate:"desc"}});res.json({success:true,data});}));
router.post("/batches",permit("SUPER_ADMIN","ORGANIZATION_ADMIN","BRANCH_ADMIN"),asyncHandler(async(req,res)=>{const input=z.object({courseId:z.string(),name:z.string().min(2),code:z.string().min(2),maxSeats:z.coerce.number().positive().optional(),startDate:z.coerce.date(),endDate:z.coerce.date().optional(),description:z.string().optional()}).parse(req.body);const course=await prisma.course.findFirst({where:{id:input.courseId,organizationId:org(req)}});if(!course)return res.status(404).json({success:false,message:"Course not found"});if(input.endDate&&input.endDate<input.startDate)return res.status(422).json({success:false,message:"End date must be after start date"});const data=await prisma.batch.create({data:{...input,branchId:branch(req),status:input.startDate>new Date()?"UPCOMING":"ACTIVE"}});await audit(req,"CREATE","Batch",data.id,data);res.status(201).json({success:true,data});}));

router.get("/attendance",asyncHandler(async(req,res)=>{const date=z.coerce.date().default(new Date(new Date().toISOString().slice(0,10)+"T00:00:00.000Z")).parse(req.query.date);const students=await prisma.student.findMany({where:{branchId:branch(req),isActive:true,deletedAt:null},include:{course:true,batch:true,attendance:{where:{date},take:1}},orderBy:{firstName:"asc"}});res.json({success:true,data:students});}));

router.route("/enquiries").get(asyncHandler(async(req,res)=>{const p=paging(req.query);const where={branchId:branch(req),...(p.search?{OR:[{visitorName:{contains:p.search,mode:"insensitive" as const}},{phone:{contains:p.search}},{personToMeet:{contains:p.search,mode:"insensitive" as const}}]}:{})};const [data,total]=await Promise.all([prisma.visitEnquiry.findMany({where,skip:p.skip,take:p.limit,orderBy:{createdAt:"desc"}}),prisma.visitEnquiry.count({where})]);res.json({success:true,data,meta:{page:p.page,limit:p.limit,total}});})).post(permit("SUPER_ADMIN","ORGANIZATION_ADMIN","BRANCH_ADMIN","RECEPTIONIST"),asyncHandler(async(req,res)=>{const input=z.object({visitorName:z.string().min(2),phone:z.string().min(10),email:z.string().email().optional(),purpose:z.enum(["ADMISSION","FEE","MEETING","COMPLAINT","DELIVERY","INTERVIEW","OTHER"]).default("OTHER"),personToMeet:z.string().min(2),department:z.enum(["ADMINISTRATION","ACADEMICS","ACCOUNTS","HR","IT","LIBRARY","SPORTS","LAB"]).default("ADMINISTRATION"),enquiryReason:z.string().optional(),remarks:z.string().optional()}).parse(req.body);const data=await prisma.visitEnquiry.create({data:{...input,branchId:branch(req),visitDate:new Date(),visitTime:new Date().toTimeString().slice(0,5)}});await audit(req,"CREATE","VisitEnquiry",data.id,data);res.status(201).json({success:true,data});}));

// Timetable endpoints
router.get("/timetable",asyncHandler(async(req,res)=>{const q=z.object({batchId:z.string().optional(),courseId:z.string().optional()}).parse(req.query);const where:Record<string,unknown>={batch:{branchId:branch(req)}};if(q.batchId)where.batchId=q.batchId;const data=await prisma.batchTiming.findMany({where,include:{batch:{include:{course:true}}},orderBy:[{batchId:"asc"},{day:"asc"},{startTime:"asc"}]});res.json({success:true,data});}));
router.post("/timetable",permit("SUPER_ADMIN","ORGANIZATION_ADMIN","BRANCH_ADMIN","TEACHER"),asyncHandler(async(req,res)=>{const input=z.object({batchId:z.string().min(2),courseId:z.string().min(2),day:z.enum(["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY"]),startTime:z.string().min(1),endTime:z.string().min(1),roomNo:z.string().optional(),subject:z.string().optional(),instructor:z.string().optional()}).parse(req.body);const batch=await prisma.batch.findFirst({where:{id:input.batchId,branchId:branch(req)}});if(!batch)return res.status(404).json({success:false,message:"Batch not found"});if(input.startTime>=input.endTime)return res.status(422).json({success:false,message:"End time must be after start time"});const clash=await prisma.batchTiming.findFirst({where:{batchId:input.batchId,day:input.day,startTime:input.startTime}});if(clash)return res.status(409).json({success:false,message:"Slot already taken"});const data=await prisma.batchTiming.create({data:{...input}});await audit(req,"CREATE","BatchTiming",data.id,data);res.status(201).json({success:true,data});}));
router.patch("/timetable/:id",permit("SUPER_ADMIN","ORGANIZATION_ADMIN","BRANCH_ADMIN","TEACHER"),asyncHandler(async(req,res)=>{const id=String(req.params.id);const existing=await prisma.batchTiming.findUnique({where:{id}});if(!existing)return res.status(404).json({success:false,message:"Slot not found"});const batch=await prisma.batch.findFirst({where:{id:existing.batchId,branchId:branch(req)}});if(!batch)return res.status(404).json({success:false,message:"Batch not found"});const input=z.object({day:z.enum(["MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY","SUNDAY"]).optional(),startTime:z.string().min(1).optional(),endTime:z.string().min(1).optional(),roomNo:z.string().optional().nullable(),subject:z.string().optional().nullable(),instructor:z.string().optional().nullable()}).parse(req.body);if(input.startTime&&input.endTime&&input.startTime>=input.endTime)return res.status(422).json({success:false,message:"End time must be after start time"});if(input.startTime){const clash=await prisma.batchTiming.findFirst({where:{batchId:existing.batchId,day:input.day??existing.day,startTime:input.startTime,NOT:{id}}});if(clash)return res.status(409).json({success:false,message:"Slot already taken"});}const data=await prisma.batchTiming.update({where:{id},data:input});await audit(req,"UPDATE","BatchTiming",id,data);res.json({success:true,data});}));
router.delete("/timetable/:id",permit("SUPER_ADMIN","ORGANIZATION_ADMIN","BRANCH_ADMIN","TEACHER"),asyncHandler(async(req,res)=>{const id=String(req.params.id);await prisma.batchTiming.delete({where:{id}});await audit(req,"DELETE","BatchTiming",id);res.status(204).send();}));

// Enquiry follow-ups and status updates
router.patch("/enquiries/:id",permit("SUPER_ADMIN","ORGANIZATION_ADMIN","BRANCH_ADMIN","RECEPTIONIST"),asyncHandler(async(req,res)=>{const id=String(req.params.id);const enquiry=await prisma.visitEnquiry.findFirst({where:{id,branchId:branch(req)}});if(!enquiry)return res.status(404).json({success:false,message:"Enquiry not found"});const input=z.object({status:z.enum(["NEW","CONTACTED","CONVERTED","CLOSED"]).optional(),followUpDate:z.coerce.date().optional(),followUpNote:z.string().optional(),followUpBy:z.string().optional(),closeNote:z.string().optional()}).parse(req.body);const updateData:Record<string,unknown>={};if(input.status)updateData.status=input.status;if(input.followUpDate)updateData.followUpDate=input.followUpDate;if(input.closeNote)updateData.closeNote=input.closeNote;if(input.followUpNote)updateData.followUpNotes=input.followUpNote;const data=await prisma.visitEnquiry.update({where:{id},data:updateData});if(input.followUpNote){await prisma.auditEvent.create({data:{actorId:req.auth!.userId,organizationId:org(req),branchId:branch(req),action:"FOLLOW_UP",entityType:"FollowUp",entityId:id,after:{note:input.followUpNote,by:input.followUpBy||req.auth!.userId},ipAddress:req.ip}});}await audit(req,"UPDATE","VisitEnquiry",id,data);res.json({success:true,data});}));

router.get("/student/profile",authenticate,asyncHandler(async(req,res)=>{const studentId=req.query.studentId as string|undefined;const student=await prisma.student.findFirst({where:{...(studentId?{id:studentId}:{userId:req.auth!.userId}),branchId:branch(req),deletedAt:null},include:{course:true,batch:true,branch:true}});if(!student)return res.status(404).json({success:false,message:"Student not found"});const fname=(student.firstName||"").trim();const lname=(student.lastName||"").trim();const mname=(student.middleName||"").trim();const displayName=[fname,mname,lname].filter(Boolean).join(" ");res.json({success:true,data:{id:student.id,enrollmentNo:student.enrollmentNo,applicationNo:student.applicationNo,name:displayName,email:student.email,phone:student.phone,whatsappNumber:student.whatsappNumber,course:student.course?.name,batch:student.batch?.name,branch:student.branch?.name,academicYear:student.academicYear,admissionDate:student.admissionDate,photo:student.photo,gender:student.gender,dateOfBirth:student.dateOfBirth,bloodGroup:student.bloodGroup,fatherName:student.fatherName,motherName:student.motherName,address:[student.streetAddress,student.city,student.state,student.pincode].filter(Boolean).join(", "),admissionStatus:student.admissionStatus}});}));

router.get("/portal/attendance",authenticate,asyncHandler(async(req,res)=>{const studentId=req.query.studentId as string|undefined;const month=z.coerce.date().optional().parse(req.query.month);const records=await prisma.attendanceRecord.findMany({where:{student:{...(studentId?{id:studentId}:{userId:req.auth!.userId}),branchId:branch(req)},...(month?{date:{gte:new Date(month.getFullYear(),month.getMonth(),1),lt:new Date(month.getFullYear(),month.getMonth()+1,1)}}:{})},include:{student:{select:{firstName:true,lastName:true,enrollmentNo:true}}},orderBy:{date:"desc"}});res.json({success:true,data:records});}));

router.get("/portal/invoices",authenticate,asyncHandler(async(req,res)=>{const studentId=req.query.studentId as string|undefined;const invoices=await prisma.feeInvoice.findMany({where:{student:{...(studentId?{id:studentId}:{userId:req.auth!.userId}),branchId:branch(req)}},include:{payments:{where:{reversedAt:null}},student:{select:{firstName:true,lastName:true,enrollmentNo:true}}},orderBy:{createdAt:"desc"}});res.json({success:true,data:invoices});}));

router.get("/portal/results",authenticate,asyncHandler(async(req,res)=>{const studentId=req.query.studentId as string|undefined;const examId=req.query.examId as string|undefined;const results=await prisma.examResult.findMany({where:{student:{...(studentId?{id:studentId}:{userId:req.auth!.userId}),branchId:branch(req)},...(examId?{examId}:{})},include:{exam:{select:{name:true,subject:true,examDate:true,maxMarks:true,passMarks:true,status:true}}},orderBy:{exam:{examDate:"desc"}}});res.json({success:true,data:results});}));

router.get("/portal/classes",authenticate,asyncHandler(async(req,res)=>{const studentId=req.query.studentId as string|undefined;const student=await prisma.student.findFirst({where:{...(studentId?{id:studentId}:{userId:req.auth!.userId}),branchId:branch(req)},select:{batchId:true}});if(!student)return res.status(404).json({success:false,message:"Student not found"});const timings=await prisma.batchTiming.findMany({where:{batchId:student.batchId??""},include:{batch:{include:{course:true}}}} as any);const today=new Date().toISOString().slice(0,10);const next7days=Array.from({length:7},(_,i)=>new Date(Date.now()+i*86400000).toISOString().slice(0,10));const dayNames=["SUNDAY","MONDAY","TUESDAY","WEDNESDAY","THURSDAY","FRIDAY","SATURDAY"];const classes=timings.map(t=>({id:t.id,subject:t.subject??"",instructor:t.instructor??"",roomNo:t.roomNo??"",startTime:t.startTime,endTime:t.endTime,day:t.day,batchId:t.batchId,course:(t as any).batch?.course?.name}));res.json({success:true,data:classes});}));

router.post("/portal/requests",authenticate,asyncHandler(async(req,res)=>{const input=z.object({kind:z.string().min(2),detail:z.string().min(3),studentId:z.string().optional()}).parse(req.body);const data=await prisma.auditEvent.create({data:{actorId:req.auth!.userId,organizationId:org(req),branchId:branch(req),action:input.kind,entityType:"PortalRequest",entityId:crypto.randomUUID(),after:{detail:input.detail,studentId:input.studentId},ipAddress:req.ip}});res.status(201).json({success:true,data});}));

// Student detail for ID cards and documents
router.get("/students/portal/:id",asyncHandler(async(req,res)=>{const id=String(req.params.id);const data=await prisma.student.findFirst({where:{id,branchId:branch(req),deletedAt:null},include:{course:true,batch:true}});if(!data)return res.status(404).json({success:false,message:"Student not found"});res.json({success:true,data});}));

router.get("/dashboard/enquiries",asyncHandler(async(req,res)=>{const data=await prisma.visitEnquiry.findMany({where:{branchId:branch(req),status:{in:["NEW","CONTACTED"]}},orderBy:{createdAt:"desc"},take:10});res.json({success:true,data});}));

router.get("/notices",asyncHandler(async(req,res)=>{const data=await prisma.branchNotice.findMany({where:{branchId:branch(req)??"__none__"},orderBy:{createdAt:"desc"},take:20});res.json({success:true,data});}));

router.route("/students").get(asyncHandler(async(req,res)=>{const p=paging(req.query);const where={branchId:branch(req),deletedAt:null,...(p.search?{OR:[{firstName:{contains:p.search,mode:"insensitive" as const}},{lastName:{contains:p.search,mode:"insensitive" as const}},{phone:{contains:p.search}},{enrollmentNo:{contains:p.search,mode:"insensitive" as const}}]}:{})};const [data,total]=await Promise.all([prisma.student.findMany({where,skip:p.skip,take:p.limit,include:{course:true,batch:true},orderBy:{createdAt:"desc"}}),prisma.student.count({where})]);res.json({success:true,data,meta:{page:p.page,limit:p.limit,total}});})).post(permit("SUPER_ADMIN","ORGANIZATION_ADMIN","BRANCH_ADMIN","RECEPTIONIST"),asyncHandler(async(req,res)=>{const input=z.object({firstName:z.string().min(2),middleName:z.string().optional(),lastName:z.string().min(1),dateOfBirth:z.coerce.date(),gender:z.enum(["MALE","FEMALE","OTHER"]),phone:z.string().min(10),email:z.string().email().optional(),streetAddress:z.string().min(3),city:z.string().min(2),state:z.string().min(2),pincode:z.string().min(6),fatherName:z.string().min(2),motherName:z.string().min(2),courseId:z.string().optional(),batchId:z.string().optional(),admissionStatus:z.enum(["DRAFT","SUBMITTED","PENDING_PAYMENT","APPROVED","REJECTED"]).default("SUBMITTED")}).parse(req.body);const data=await prisma.student.create({data:{...input,branchId:branch(req),applicationNo:documentNo("APP")}});await audit(req,"CREATE","Student",data.id,data);res.status(201).json({success:true,data});}));
router.get("/students/:id",asyncHandler(async(req,res)=>{const id=String(req.params.id);const data=await prisma.student.findFirst({where:{id,branchId:branch(req),deletedAt:null},include:{course:true,batch:true,feeInvoices:{include:{payments:true}},attendance:{take:30,orderBy:{date:"desc"}}}});if(!data)return res.status(404).json({success:false,message:"Student not found"});res.json({success:true,data});}));

router.route("/courses").get(asyncHandler(async(req,res)=>{const data=await prisma.course.findMany({where:{organizationId:org(req),deletedAt:null},include:{_count:{select:{students:true,batches:true}}},orderBy:{name:"asc"}});res.json({success:true,data});})).post(permit("SUPER_ADMIN","ORGANIZATION_ADMIN","BRANCH_ADMIN"),asyncHandler(async(req,res)=>{const input=z.object({name:z.string().min(2),code:z.string().min(2),category:z.enum(["COMPUTER","VOCATIONAL","ACADEMIC","LANGUAGE","PROFESSIONAL","SKILL_DEVELOPMENT","OTHER"]),durationValue:z.coerce.number().positive(),durationUnit:z.enum(["DAYS","WEEKS","MONTHS","YEARS"]),baseFee:z.coerce.number().nonnegative(),registrationFee:z.coerce.number().nonnegative().default(0),examFee:z.coerce.number().nonnegative().default(0),description:z.string().optional()}).parse(req.body);const data=await prisma.course.create({data:{...input,organizationId:org(req)}});await audit(req,"CREATE","Course",data.id,data);res.status(201).json({success:true,data});}));

router.route("/fees/invoices").get(asyncHandler(async(req,res)=>{const data=await prisma.feeInvoice.findMany({where:{branchId:branch(req)},include:{student:{select:{firstName:true,lastName:true,enrollmentNo:true}},payments:{where:{reversedAt:null}}},orderBy:{createdAt:"desc"}});res.json({success:true,data});})).post(permit("SUPER_ADMIN","ORGANIZATION_ADMIN","BRANCH_ADMIN","ACCOUNTANT"),asyncHandler(async(req,res)=>{const input=z.object({studentId:z.string(),description:z.string().min(2),amount:z.coerce.number().positive(),dueDate:z.coerce.date()}).parse(req.body);const student=await prisma.student.findFirst({where:{id:input.studentId,branchId:branch(req)}});if(!student)return res.status(404).json({success:false,message:"Student not found"});const data=await prisma.feeInvoice.create({data:{...input,branchId:branch(req),invoiceNo:documentNo("INV")}});await audit(req,"CREATE","FeeInvoice",data.id,data);res.status(201).json({success:true,data});}));
router.post("/fees/invoices/:id/payments",permit("SUPER_ADMIN","ORGANIZATION_ADMIN","BRANCH_ADMIN","ACCOUNTANT"),asyncHandler(async(req,res)=>{const input=z.object({amount:z.coerce.number().positive(),method:z.enum(["CASH","UPI","CARD","BANK_TRANSFER","CHEQUE"]),referenceNo:z.string().optional()}).parse(req.body);const id=String(req.params.id);const branchId=branch(req);const result=await prisma.$transaction(async tx=>{
  // Lock the invoice row first. Reading the balance outside the transaction let
  // concurrent payments each see the same outstanding amount and all pass the
  // check, overpaying the invoice.
  const locked=await tx.$queryRaw<{amount:string}[]>`SELECT "amount" FROM "fee_invoices" WHERE "id"=${id} AND "branchId"=${branchId} FOR UPDATE`;
  if(!locked.length)throw new ErrorResponse("Invoice not found",404,"NOT_FOUND");
  const total=paise(locked[0].amount);
  const settled=await tx.feePayment.aggregate({where:{invoiceId:id,reversedAt:null},_sum:{amount:true}});
  const next=paise(settled._sum.amount)+paise(input.amount);
  if(next>total)throw new ErrorResponse("Payment exceeds outstanding balance",422,"UNPROCESSABLE_ENTITY");
  const payment=await tx.feePayment.create({data:{...input,invoiceId:id,receiptNo:documentNo("RCT"),receivedById:req.auth!.userId}});
  await tx.feeInvoice.update({where:{id},data:{status:next===total?"PAID":"PARTIAL"}});
  return payment;
});await audit(req,"PAYMENT_RECEIVED","FeeInvoice",id,result);res.status(201).json({success:true,data:result});}));

router.post("/attendance",permit("SUPER_ADMIN","ORGANIZATION_ADMIN","BRANCH_ADMIN","TEACHER"),asyncHandler(async(req,res)=>{const input=z.object({date:z.coerce.date(),records:z.array(z.object({studentId:z.string(),status:z.enum(["PRESENT","ABSENT","LATE","EXCUSED"]),remarks:z.string().optional()})).min(1)}).parse(req.body);const ids=input.records.map(r=>r.studentId);const valid=await prisma.student.count({where:{id:{in:ids},branchId:branch(req)}});if(valid!==new Set(ids).size)return res.status(422).json({success:false,message:"One or more students do not belong to this branch"});const data=await prisma.$transaction(input.records.map(record=>prisma.attendanceRecord.upsert({where:{studentId_date:{studentId:record.studentId,date:input.date}},create:{...record,date:input.date,branchId:branch(req),markedById:req.auth!.userId},update:{status:record.status,remarks:record.remarks,markedById:req.auth!.userId}})));await audit(req,"ATTENDANCE_MARKED","Attendance",undefined,{date:input.date,count:data.length});res.json({success:true,data});}));
router.route("/exams").get(asyncHandler(async(req,res)=>{const data=await prisma.exam.findMany({where:{branchId:branch(req)},include:{course:true,batch:true,results:{include:{student:{select:{firstName:true,lastName:true,enrollmentNo:true}}}}},orderBy:{examDate:"desc"}});res.json({success:true,data});})).post(permit("SUPER_ADMIN","ORGANIZATION_ADMIN","BRANCH_ADMIN","TEACHER"),asyncHandler(async(req,res)=>{const input=z.object({courseId:z.string(),batchId:z.string().optional(),name:z.string().min(2),subject:z.string().min(2),examDate:z.coerce.date(),maxMarks:z.coerce.number().int().positive().default(100),passMarks:z.coerce.number().int().nonnegative().default(40)}).parse(req.body);if(input.passMarks>input.maxMarks)return res.status(422).json({success:false,message:"Pass marks cannot exceed maximum marks"});const course=await prisma.course.findFirst({where:{id:input.courseId,organizationId:org(req)}});if(!course)return res.status(404).json({success:false,message:"Course not found"});const data=await prisma.exam.create({data:{...input,branchId:branch(req)}});await audit(req,"CREATE","Exam",data.id,data);res.status(201).json({success:true,data});}));

router.post("/exams/:id/results",permit("SUPER_ADMIN","ORGANIZATION_ADMIN","BRANCH_ADMIN","TEACHER"),asyncHandler(async(req,res)=>{const id=String(req.params.id);const input=z.object({results:z.array(z.object({studentId:z.string(),marks:z.coerce.number().nonnegative(),remarks:z.string().optional()})).min(1),publish:z.boolean().default(false)}).parse(req.body);const exam=await prisma.exam.findFirst({where:{id,branchId:branch(req)}});if(!exam)return res.status(404).json({success:false,message:"Exam not found"});if(input.results.some(result=>result.marks>exam.maxMarks))return res.status(422).json({success:false,message:`Marks cannot exceed ${exam.maxMarks}`});const ids=input.results.map(result=>result.studentId);const valid=await prisma.student.count({where:{id:{in:ids},branchId:branch(req),courseId:exam.courseId}});if(valid!==new Set(ids).size)return res.status(422).json({success:false,message:"One or more students are outside this course"});const data=await prisma.$transaction(async tx=>{const results=await Promise.all(input.results.map(result=>tx.examResult.upsert({where:{examId_studentId:{examId:id,studentId:result.studentId}},create:{examId:id,...result},update:{marks:result.marks,remarks:result.remarks}})));await tx.exam.update({where:{id},data:{status:input.publish?"PUBLISHED":"MARKS_ENTRY"}});return results});await audit(req,input.publish?"RESULTS_PUBLISHED":"MARKS_SAVED","Exam",id,{count:data.length});res.json({success:true,data});}));

router.get("/documents/students/:id",asyncHandler(async(req,res)=>{const data=await prisma.student.findFirst({where:{id:String(req.params.id),branchId:branch(req),deletedAt:null},include:{branch:{include:{organization:true,address:true}},course:true,batch:true,feeInvoices:{include:{payments:{where:{reversedAt:null}}}},examResults:{include:{exam:true},orderBy:{exam:{examDate:"desc"}}}}});if(!data)return res.status(404).json({success:false,message:"Student not found"});res.json({success:true,data});}));

export default router;
