import request from "supertest";import{afterAll,describe,expect,it}from"vitest";import app from"./app";import{prisma}from"./db";
declare global { namespace NodeJS { interface Global { __studentId?: string; __invoiceId?: string; __courseId?: string; __batchId?: string } } }
const run=process.env.RUN_DB_TESTS==="1"?describe:describe.skip;
run("database-backed operational chain",()=>{
  let token="";let organizationId="";let branchId="";
  it("bootstraps a fresh organisation",async()=>{const r=await request(app).post("/api/v1/auth/bootstrap").set("x-bootstrap-token",process.env.BOOTSTRAP_TOKEN||"").send({organizationName:"Test Org",adminName:"Test Admin",email:"admin@test.local",phone:"9999999999",password:"TestPass123!",branchName:"Test Branch",city:"Test City",state:"Test State",pincode:"000001"});expect(r.status).toBe(201);expect(r.body.data.adminEmail).toBe("admin@test.local");organizationId=r.body.data.organizationId;branchId=r.body.data.branchId});
  it("authenticates the administrator",async()=>{const r=await request(app).post("/api/v1/auth/login").send({identifier:"admin@test.local",password:"TestPass123!"});expect(r.status).toBe(200);token=r.body.data.accessToken});
  it("creates an admitted student",async()=>{const course=await request(app).post("/api/v1/core/courses").set("Authorization",`Bearer ${token}`).send({organizationId,name:"Test Course",code:"TEST-COURSE-1",category:"COMPUTER",durationValue:12,durationUnit:"MONTHS",baseFee:36000,registrationFee:1000,examFee:1500,description:"Test course"});expect(course.status).toBe(201);const batch=await request(app).post("/api/v1/core/batches").set("Authorization",`Bearer ${token}`).send({organizationId,branchId,courseId:course.body.data.id,name:"Test Batch",code:"TEST-BATCH-1",maxSeats:30,startDate:"2026-01-01",endDate:"2026-12-31",status:"ACTIVE"});expect(batch.status).toBe(201);const r=await request(app).post("/api/v1/core/students").set("Authorization",`Bearer ${token}`).send({organizationId,branchId,firstName:"Integration",lastName:"Student",dateOfBirth:"2005-01-01",gender:"OTHER",phone:"9777700001",email:"integration.student@test.local",streetAddress:"Test Road",city:"Test City",state:"Test State",pincode:"000001",fatherName:"Test Guardian",motherName:"Test Parent",courseId:course.body.data.id,batchId:batch.body.data.id,admissionStatus:"APPROVED"});expect(r.status).toBe(201);global.__studentId=r.body.data.id;global.__courseId=course.body.data.id;global.__batchId=batch.body.data.id});
  it("creates an invoice and records a payment",async()=>{const invoice=await request(app).post("/api/v1/core/fees/invoices").set("Authorization",`Bearer ${token}`).send({organizationId,branchId,studentId:global.__studentId,description:"Integration fee",amount:1000,dueDate:"2026-09-01"});expect(invoice.status).toBe(201);global.__invoiceId=invoice.body.data.id;const payment=await request(app).post(`/api/v1/core/fees/invoices/${global.__invoiceId}/payments`).set("Authorization",`Bearer ${token}`).send({amount:1000,method:"UPI",referenceNo:"TEST-UPI"});expect(payment.status).toBe(201);expect(payment.body.data.receiptNo).toMatch(/^RCT-/)});
  it("marks student attendance",async()=>{const r=await request(app).post("/api/v1/core/attendance").set("Authorization",`Bearer ${token}`).send({organizationId,branchId,batchId:global.__batchId,date:"2026-08-13",records:[{studentId:global.__studentId,status:"PRESENT"}]});expect(r.status).toBe(200);expect(r.body.data).toHaveLength(1)});
  afterAll(async()=>{if(global.__studentId){await prisma.attendanceRecord.deleteMany({where:{studentId:global.__studentId}});if(global.__invoiceId){await prisma.feePayment.deleteMany({where:{invoiceId:global.__invoiceId}});await prisma.feeInvoice.deleteMany({where:{studentId:global.__studentId}})}await prisma.student.delete({where:{id:global.__studentId}})}await prisma.$disconnect()});
});
